name: Networking Tests

on:
  workflow_dispatch:
  push:

jobs:
  build:
    
    name: Test ${{ matrix.project }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    
    environment: test
    
    env:
      NEXUS_API_KEY: ${{ secrets.NEXUS_API_KEY }}
    
    strategy:
      matrix:
        #os: [ubuntu-latest, windows-latest, macos-latest]
        os: [self-hosted]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
          lfs: true

      - name: Print debug info
        run: dotnet --info

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Tests
        run: dotnet test --no-build --logger "GitHubActions" --filter "RequiresNetworking!=True" --collect:"XPlat Code Coverage;Format=opencover" --blame-hang-timeout 20m

